seed: 42
batch_size: 32
epochs_phase1: 10
lr_phase1: 0.001
epochs_phase2: 20
lr_phase2: 0.0001
model_name: 'densenet'
splits_dir: 'data/splits'
use_weighted_sampler: false
use_focal_loss: true
save_path: 'outputs/models/densenet_best.pth'
project_name: 'csc4005-khmt16-01-skin-lesion-classification'
patience: 5
