seed: 42
batch_size: 32
epochs_phase1: 10
lr_phase1: 0.001
epochs_phase2: 20
lr_phase2: 0.0001
model_name: 'efficientnet'
splits_dir: 'data/splits'
use_weighted_sampler: true
sampler_beta: 0.35
loss_beta: 0.25
use_focal_loss: true
save_path: 'outputs/models/efficientnet_best.pth'
project_name: 'csc4005-khmt16-01-skin-lesion-classification'
patience: 5
remove_hair: true


